### PR TITLE
Ammo reloading

### LINKED ISSUE #19: Add ammo and reloading

### PR DESCRIPTION
**Pull request by Dukeman330**
Fixes #19

### CODE REVIEW

**Comment by Dukeman330** [comment]
Press 'R' or try firing with an empty clip to reload

**Comment by linqiu** [comment]
Nice mechanism! I think we can tweak the timing of the reload but that can go in after. But I do think that the upper left might be too far away to see. It should maybe be next to the player's box? i feel like you're gonna be constantly looking away from the middle ofhte action to see what's going on.

**Comment by seanperkins** [comment]
@rickymetz  had a cool mechanism for showing ammo behind the character box. You should hit him up.

**Comment by Dukeman330** [comment]
cool, will do.  I was thinking of the ammo display in more of a "heads up display" sense but putting it right there under the player would def. keep things more immediate

**Comment by STRML** [comment]
FYI I've rebased this onto master. When we merge the `refactor-lighting` branch we'll need to fix the `Utilities` import - we shouldn't be requiring like `require('./module')()`.

**Comment by STRML** [comment]
The `build` directory is gone so this will be easier to merge.

**Comment by linqiu** [comment]
yeah i don't like the way we're doing `require('./module')()` :(

**Comment by STRML** [comment]
Merged into master as of 5ce52f9938f1adf2f65682e14e3f66bf9b35fe3d.

**Pull request closed without merging**
