### PR TITLE
get on outta here, build. we don't need your kind around here

### PR DESCRIPTION
**Pull request by Dukeman330**
Can we pleeease get rid of this.  It's making me sad when I try to merge.

### CODE REVIEW

**Comment by seanperkins** [comment]
hmmmm....how are we gonna load the build on heroku? It is currently auto loading what is on master onto the dyno.

**Comment by Dukeman330** [comment]
oh... is there no post-upload build command we can run on heroku?  not terribly familiar with heroku

**Comment by seanperkins** [comment]
We can add it to the package.json to run a build command. We were
discussing it last night. It is possible a merge to master will break
things but that might be an ok risk.

**Comment by Dukeman330** [comment]
at this stage in dev I think it'd def. be an ok risk.  in the mean time, seems like it'd be a lot better to not have the build files clogging up merges and commit logs.  just my 2 cents.

**Comment by linqiu** [comment]
yeah i really don't like the way we're merging the build stuff and having to deal with rebase issues on app.min.js my mergetool takes forever to pick a commit. i always just rando pick one and then blow it away on when i rebuild. it's getting annoying

**Comment by STRML** [comment]
Yeah a makefile that builds and pushes to a release branch would be good,
otherwise let's just have Heroku build on deploy

**Comment by STRML** [comment]
:shipit:?

**Pull request merged**
