### PR TITLE
Place the bullets behind the player [Ready to merge]

### PR DESCRIPTION
**Pull request by seanperkins**
@Dukeman330 Look at this. I moved the bullets behind the player by adding them as children.

I was thinking we could place the bullets in 2 groups of three so they are the width of the player.

I created this as a PR because I just wanted to show you what we could do.

### CODE REVIEW

**Comment by STRML** [comment]
:shipit:

**Comment by seanperkins** [comment]
:+1:

**Comment by STRML** [comment]
Not sure what GitHub's problem is - this cleanly merges. If you guys are okay with it I'll throw it in master.

**Comment by STRML** [comment]
Oh I see the issue - you're merging from place_bullets_behind into ammo-reloading...

**Comment by linqiu** [comment]
:+1:

**Comment by STRML** [comment]
I'm going to merge this into master and then we'll just delete the branches rather than untangle this mess.

**Comment by STRML** [comment]
This can be closed, merged into master as of 5ce52f9938f1adf2f65682e14e3f66bf9b35fe3d

**Pull request closed without merging**
