### PR TITLE
added lodash back into dependencies

### PR DESCRIPTION
**Pull request by Dukeman330**

### CODE REVIEW

**Comment by linqiu** [comment]
i don't understand how we lost this?

**Comment by Dukeman330** [comment]
it disappeared when sam was ripping out other stuff

**Comment by STRML** [comment]
That's not so, it wasn't in `dependencies` to begin with.

**Comment by Dukeman330** [comment]
oops, my bad - it was @seanperkins 

https://github.com/seanperkins/the-walking-box/commit/9971c3fdd45ea458055188cd1330322e271bebbd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by linqiu** [comment]
that was a cowboy master push. GOOD JOB, SEAN!

**Comment by linqiu** [comment]
:+1:

**Comment by seanperkins** [comment]
You were sitting right next to me Lin. :+1: Chris

**Pull request merged**
